config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'recipes#index'
    resources :recipes do
        resource :favorites, only: [:create, :destroy]
        collection do
            get 'search'
        end
    end
    resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cooking_time.rb
class CookingTime < ActiveHash::Base
    self.data = [
      { id: 1, name: '---' },
      { id: 2, name: '10分以下' },
      { id: 3, name: '20分' },
      { id: 4, name: '30分' },
      { id: 5, name: '1時間' },
      { id: 6, name: '1時間30分' },
      { id: 7, name: '2時間以上' }
    ]

    include ActiveHash::Associations
    has_many :recipes, class_name: 'Recipe'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :recipe, inverse_of: :foods

    validates :name, presence: true
    validates :quantity, presence: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
    belongs_to :recipe, inverse_of: :procedures

    validates :cooking_method, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :cooking_time, class_name: 'CookingTime'
    has_many :foods, inverse_of: :recipe, dependent: :destroy
    has_many :procedures, inverse_of: :recipe, dependent: :destroy
    accepts_nested_attributes_for :foods, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :procedures, reject_if: :all_blank, allow_destroy: true
    has_many :favorites, dependent: :destroy

    has_one_attached :image

    validates :image, presence: true
    validates :title, presence: true
    validates :cooking_time_id, presence: true, numericality: { other_than: 1 }
    validates_presence_of :foods, message: "料理の材料を入力してください"
    validates_presence_of :procedures, message: "料理の作り方を入力してください"

    def self.search(search)
      if search.present?
          Recipe.where('title LIKE ?', "%#{search}%")
      else
          Recipe.all
      end
    end

    def favorited_by?(user)
        favorites.where(user_id: user_id).exists?
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :favorites, dependent: :destroy
    has_many :favorited_recipes, through: :favorites, source: :recipe
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    validates :nickname, presence: true

    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
    validates :password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :basic_auth
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def basic_auth
        authenticate_or_request_with_http_basic do |username, password|
            username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
        end
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_recipe, only: [:create, :destroy]

    def create
        favorite = current_user.favorites.build(recipe_id: params[:recipe_id])
        favorite.save
        render partial: "favorites/btn", locals: { recipe: @recipe }
    end
    
    def destroy
        favorite = Favorite.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)
        favorite.destroy
        render partial: "favorites/btn", locals: { recipe: @recipe }
    end


    def set_recipe
        @recipe = Recipe.find(params[:recipe_id])
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    before_action :move_to_index, only: [:edit, :destroy]

    def index
        @recipes = Recipe.all
        respond_to do |format|
            format.html
            format.json { render json: @recipes }
        end
    end

    def new
        @recipe = Recipe.new
        @recipe.foods.build
        @recipe.procedures.build
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)
            redirect_to recipe_path(@recipe.id)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @recipe.destroy
        redirect_to root_path
    end

    def search
        @recipes = Recipe.search(params[:keyword])
    end

    private
    def recipe_params
        params.require(:recipe).permit(:image, :title, :cooking_time_id, foods_attributes: [:id, :name, :quantity, :_destroy], procedures_attributes: [:id, :cooking_method, :_destroy]).merge(user_id: current_user.id)
    end

    def find_recipe
        @recipe = Recipe.find(params[:id])
    end

    def move_to_index
        unless @recipe.user_id == current_user.id
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        user = User.find(params[:id])
        @nickname = user.nickname
        @recipes = user.recipes
        @favorited_recipes = user.favorited_recipes
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_btn.html.erb
<% if user_signed_in? %>
<div class="favorite-area">
    <%= turbo_frame_tag dom_id(recipe, :favorite) do %>
        <% if recipe.favorited_by?(current_user) %>
            <%= link_to recipe_favorites_path(recipe), data: { turbo_method: :delete, turbo_frame: "favorite-btn#{recipe.id}" }, class: "favorite-btn" do %>
                <i class="fa-solid fa-star" aria-hidden="true" style="color: orange;"></i>
                <%= recipe.favorites.count %>
            <% end %>
        <% else %>
            <%= link_to recipe_favorites_path(recipe), data: { turbo_method: :post, turbo_frame: "favorite-btn#{recipe.id}" }, class: "favorite-btn" do %>
                <i class="fa-solid fa-star" aria-hidden="true"></i>
                <%= recipe.favorites.count %>
            <% end %>
        <% end %>
    <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RondomRecipe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&family=M+PLUS+Rounded+1c:wght@300&family=Noto+Sans+JP:wght@300&family=Oswald:wght@700&family=Rampart+One&family=Roboto:wght@100&family=Space+Grotesk:wght@700&family=Work+Sans:ital,wght@0,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
  <script src="https://kit.fontawesome.com/b01307851e.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= render "shared/second-header" %>

<div class="recipe-post-container">
    <%= form_with model: @recipe, class: 'recipe-post-form', id: 'new_post', local: true do |f| %>

    <%= render 'shared/error_messages', model: @recipe %>

        <div class="recipe-post-main">
            <div class="recipe-post-top">
                <h1>レシピ編集</h1>
            </div>
            <div id="preview"></div>
            <div class="recipe-form-area">
                <div id="previews"></div>
                <p class="recipe-post-text">料理写真<span class="indispensable">(必須)</span></p>
                <%= f.file_field :image, id:"recipe-image" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">料理名<span class="indispensable">(必須)</span></p>
                <%= f.text_area :title, class:"recipe-title-text", id:"recipe-title", maxlength:"40" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">調理時間<span class="indispensable">(必須)</span></p>
                <%= f.collection_select(:cooking_time_id, CookingTime.all, :id, :name, {}, {class:"select-box", id:"cooking_time"}) %>
            </div>
            <div class="recipe-form-area">
                <div class="recipe-post-texts">
                    <p class="recipe-post-text">材料<span class="indispensable">(必須)</span></p>
                    <p class="recipe-post-text">数量<span class="indispensable">(必須)</span></p>
                </div>
                <%= f.fields_for :foods do |food_form| %>
                    <div id="foods-container">
                        <%= food_form.text_field :name %>
                        <%= food_form.text_field :quantity, class: "quantity" %>
                        <!--<%= link_to '削除', "#", class: "delete-food-btn" %>-->
                    </div>
                <% end %>
                <p class="add-form"><%= link_to '材料を追加', "#", id: "add-food-btn" %></p>
                <div id="foods_fields_template" style="display: none;">
                    <%= f.fields_for :foods, Food.new, child_index: 'new_foods' do |food_form| %>
                        <%= food_form.text_field :name %>
                        <%= food_form.text_field :quantity, class: "quantity" %>
                        <!--<%= link_to '削除', "#", class: "delete-food-btn" %>-->
                    <% end %>
                </div>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">作り方<span class="indispensable">(必須)</span></p>
                <%= f.fields_for :procedures do |procedure_form| %>
                    <div id="procedures-container">
                        <%= procedure_form.text_area :cooking_method, class: "cooking-method" %>
                        <!--<%= link_to '削除', "#", class: "delete-procedure-btn" %>-->
                    </div>
                <% end %>
                <p class="add-form"><%= link_to '作り方を追加', "#", id: "add-procedure-btn" %></p>
                <div id="procedures_fields_template" style="display: none;">
                    <%= f.fields_for :procedures, Procedure.new, child_index: 'new_procedures' do |procedure_form| %>
                        <%= procedure_form.text_area :cooking_method, class: "cooking-method" %>
                        <!--<%= link_to '削除', "#", class: "delete-procedure-btn" %>-->
                    <% end %>
                </div>
            </div>


            <div class="btn-area">
                <div class="recipe-post">
                    <%= f.submit "編集", class:"recipe-post-btn" %>
                </div>
                <div class="back">
                    <%= link_to '戻る', :back, class:"back-btn" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<%= render "shared/footer" %>

app/views/recipes/index.html.erb
<%= render "shared/header" %>

<main>
    <div class="main-container">
        <div class="main-top">
            <div class="main-top-text">
                <p>自分のレシピを投稿しよう！</p>
            </div>
            <div class="swiper-container">
                <div class="swiper infinite-slider">
                    <div class="swiper-wrapper">
                    <div class="swiper-slide"><%= image_tag 'recipe1.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe2.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe3.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe4.jpeg' %></div>
                    <div class="swiper-slide"><%= image_tag 'recipe5.jpeg' %></div>
                </div>
            </div>
        </div>


        <div class="slot-container">
            <div class="slot-texts">
                <p class="slot-text">今日の献立に困ったら...</p>
                <%= image_tag '矢印アイコン　下6.png', class: "slot-text-img" %>
                <p class="slot-text">運に任せよう‼️</p>
            </div>
            <div class="slot-area">
                <div class="slot">
                    <div class="slot-inner" id="slot-inner">
                    </div>
                </div>
                <div class="buttons">
                    <button class="start-button" id="start-button">スタート</button>
                    <button class="stop-button" id="stop-button">ストップ</button>
                </div>
            </div>
        </div>


        <div class="main-area">
            <div class="recipes-container">
                <div class="recipes-list-text">
                    <%= image_tag 'フォークとナイフのお食事アイコン素材2.png', class: "text-icon" %>
                    <h2 class="recipe-lists-title">レシピ一覧</h2>
                </div>

                <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
                    <%= form.text_field :keyword, placeholder: "レシピを検索する", class: "search-input" %>
                    <%= form.button nil, class: "search-btn" do %>
                        <%= image_tag("検索アイコン1.png", alt: "検索") %>
                    <% end %>
                <% end %>

                <div class="recipe-area">
                    <ul class="recipe-lists">
                        <% @recipes.each do |recipe| %>
                            <li class="recipe-list">
                                <%= link_to recipe_path(recipe.id) do %>
                                    <div class="image-content">
                                        <%= image_tag recipe.image, class: "recipe-image" %>
                                    </div>
                                <% end %>
                                <div class="recipe-texts">
                                    <p class="recipe-title"><%=link_to recipe.title, recipe_path(recipe.id) %></p>
                                    <p class="cooking-time">調理時間目安：<%= recipe.cooking_time[:name] %></p>
                                    <div class="recipe-texts-flex">
                                        <p class="recipe-user"><%= link_to "投稿者：#{recipe.user.nickname}", user_path(recipe.user_id) %></p>
                                        <div id="fovorite-btn<%= recipe.id %>">
                                            <%= render "favorites/btn", recipe: recipe %>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
            <%= render "shared/footer" %>
        </div>
    </div>
</main>

app/views/recipes/new.html.erb
<%= render "shared/second-header" %>

<div class="recipe-post-container">
    <%= form_with model: @recipe, class: 'recipe-post-form', id: 'new_post', local: true do |f| %>

    <%= render 'shared/error_messages', model: @recipe %>

        <div class="recipe-post-main">
            <div class="recipe-post-top">
                <h1>レシピ情報入力</h1>
            </div>
            <div class="recipe-form-area">
                <div id="previews"></div>
                <p class="recipe-post-text">料理写真<span class="indispensable">(必須)</span></p>
                <%= f.file_field :image, id:"recipe-image" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">料理名<span class="indispensable">(必須)</span></p>
                <%= f.text_area :title, class:"recipe-title-text", id:"recipe-title", maxlength:"40" %>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">調理時間<span class="indispensable">(必須)</span></p>
                <%= f.collection_select(:cooking_time_id, CookingTime.all, :id, :name, {}, {class:"select-box", id:"cooking_time"}) %>
            </div>
            <div class="recipe-form-area">
                <div class="recipe-post-texts">
                    <p class="recipe-post-text">材料<span class="indispensable">(必須)</span></p>
                    <p class="recipe-post-text">数量<span class="indispensable">(必須)</span></p>
                </div>
                <%= f.fields_for :foods do |food_form| %>
                    <div id="foods-container">
                        <%= food_form.text_field :name, class: "name" %>
                        <%= food_form.text_field :quantity, class: "quantity" %>
                    </div>
                <% end %>
                <p class="add-form"><%= link_to '材料を追加', "#", id: "add-food-btn" %></p>
                <div id="foods_fields_template" style="display: none;">
                    <%= f.fields_for :foods, Food.new, child_index: 'new_foods' do |food_form| %>
                        <%= food_form.text_field :name %>
                        <%= food_form.text_field :quantity, class: "quantity" %>
                    <% end %>
                </div>
            </div>
            <div class="recipe-form-area">
                <p class="recipe-post-text">作り方<span class="indispensable">(必須)</span></p>
                <%= f.fields_for :procedures do |procedure_form| %>
                    <div id="procedures-container">
                        <%= procedure_form.text_area :cooking_method, class: "cooking-method" %>
                    </div>
                <% end %>
                <p class="add-form"><%= link_to '作り方を追加', "#", id: "add-procedure-btn" %></p>
                <div id="procedures_fields_template" style="display: none;">
                    <%= f.fields_for :procedures, Procedure.new, child_index: 'new_procedures' do |procedure_form| %>
                        <%= procedure_form.text_area :cooking_method, class: "cooking-method" %>
                    <% end %>
                </div>
            </div>


            <div class="btn-area">
                <div class="recipe-post">
                    <%= f.submit "投稿" ,class:"recipe-post-btn" %>
                </div>
                <div class="back">
                    <%=link_to '戻る', root_path, class:"back-btn" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<%= render "shared/footer" %>

app/views/recipes/search.html.erb
<%= render "shared/second-header" %>

<main>
    <div class="main-container">
        <div class="main-area">
            <div class="search-recipes-container">
                

                <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |form| %>
                    <%= form.text_field :keyword, placeholder: "レシピを検索する", class: "search-input" %>
                    <%= form.button nil, class: "search-btn" do %>
                        <%= image_tag("検索アイコン1.png", alt: "検索") %>
                    <% end %>
                <% end %>

                <div class="search-recipe-area">
                    <ul class="recipe-lists">
                        <% @recipes.each do |recipe| %>
                            <li class="recipe-list">
                                <%= link_to recipe_path(recipe.id) do %>
                                    <div class="image-content">
                                        <%= image_tag recipe.image, class: "recipe-image" %>
                                    </div>
                                <% end %>
                                <div class="recipe-texts">
                                    <p class="recipe-title"><%=link_to recipe.title, recipe_path(recipe.id) %></p>
                                    <p class="cooking-time">調理時間目安：<%= recipe.cooking_time[:name] %></p>
                                    <div class="recipe-texts-flex">
                                        <p class="recipe-user"><%= link_to "投稿者：#{recipe.user.nickname}", user_path(recipe.user_id) %></p>
                                        <div id="fovorite-btn<%= recipe.id %>">
                                            <%= render "favorites/btn", recipe: recipe %>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>

<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/modal" %>

<%= render "shared/second-header" %>

<div class="show-container">
    <div class="show-area">
        <div class="show-recipe">
            <div class="show-flex">
                <div class="show-recipe-left">
                    <div class="show-image-area">
                        <%= image_tag @recipe.image, class: "show-image" %>
                    </div>
                    <h2 class="show-title"><%= @recipe.title %></h2>
                    <div class="show-text-flex">
                        <p class="show-cooking-time">調理時間目安：<%= @recipe.cooking_time[:name] %></p>
                        <p class="show-recipe-user"><%= link_to "投稿者：#{@recipe.user.nickname}", user_path(@recipe.user_id) %></p>
                        <%= render "favorites/btn", recipe: @recipe %>
                    </div>
                </div>

                <div class="show-recipe-right">
                    <div class="food-responsive">
                        <p class="food-texts-title">材料</p>
                        <ul class="food-area">
                           <% @recipe.foods.each do |food| %>
                                <div class="food-flex">
                                    <li class="show-food-text"><%= food.name %></li>
                                    <li class="show-food-text"><%= food.quantity %></li>
                                </div>
                            <% end %>
                        </ul>
                    </div>
                    <div class="procedure-responsive">
                        <p class="procedure-texts-title">作り方</p>
                        <ol class="procedure-area">
                            <% @recipe.procedures.each do |procedure| %>
                                <li class="show-procedure"><%= procedure.cooking_method %></li>
                            <% end %>
                        </ol>
                    </div>
                </div>
            </div>
            <% if user_signed_in? && current_user.id == @recipe.user_id %>
            <div class="show-button-area">
                <div class="edit">
                    <%= link_to '編集', edit_recipe_path(@recipe.id), class: "edit-btn" %>
                </div>
                <div class="delete">
                    <a href="#" class="delete-btn" id="openModal">削除</a>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="footer-text">
    © Rundom Recipe
    </div>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
    <div class="header-container">
        <div class="header-left">
            <%= image_tag 'ルーレット.jpeg', class: "icon" %>
            <h1><%= link_to 'RandomRecipe', "#", class: "app-title" %></h1>
        </div>
        <div class="header-right">
            <ul>
                <% if user_signed_in? %>
                    <li><%= link_to current_user.nickname, user_path(current_user.id), class: "nickname" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout" %></li>
                    <div class="recipes-create"><%= link_to 'レシピ投稿', new_recipe_path, class: "recipes-create-btn" %></div>
                <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
                    <div class="recipes-create"><%= link_to 'レシピ投稿', new_recipe_path, class: "recipes-create-btn" %></div>
                <% end %>
            </ul>
            <div class="ham-images">
                <div class="recipes-create"><%= link_to 'レシピ投稿', new_recipe_path, class: "recipes-create-btn" %></div>
                <%= image_tag 'ham-menu-image01.png', class: "ham-img1", id: "open_hum" %>
                <%= image_tag 'ham-menu-image02.png', class: "ham-img2", id: "close_hum" %>
            </div>
        </div>
        <div class="ham-menu" id="hum_menu">
            <ul>
                <% if user_signed_in? %>
                    <li><%= link_to current_user.nickname, user_path(current_user.id), class: "ham-nickname" %></li>
                    <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "ham-logout" %></li>
                <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path, class: "ham-login" %></li>
                    <li><%= link_to '新規登録', new_user_registration_path, class: "ham-sign-up" %></li>
                <% end %>
            </ul>
        </div>
    </div>
</header>

app/views/shared/_modal.html.erb
<div class="modal" id="confirmationModal">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">確認</h5>
            <button class="close-modal-button" id="closeModal">&times;</button>
        </div>
        <div class="modal-body">
            本当に削除しますか？
        </div>
        <div class="modal-footer">
            <button class="cancel-modal-button" id="cancelDelete">キャンセル</button>
            <%= link_to '削除', recipe_path(@recipe.id), data: { turbo_method: :delete }, class: "recipe-delete" %>
        </div>
    </div>
</div>

app/views/shared/_second-header.html.erb
<div class='second-header'>
    <div class="second-header-container">
        <%= image_tag 'ルーレット.jpeg', class: "icon" %>
        <h1><%= link_to 'RandomRecipe', root_path, class: "app-title" %></h1>
    </div>
</div>

app/views/users/show.html.erb
<%= render "shared/second-header" %>

<div class="my-page-container">
    <div class="my-page-area">
        <div class="information">
            <p class="information-nickname"><%= @nickname %></p>
        </div>
        <div class="my-recipe">
            <div class="recipe-favorite-flex">
                <button class="my-recipe-text" id="my-recipe-text">投稿一覧</button>
                <button class="my-favorite-text" id="my-favorite-text">お気に入り一覧</button>
            </div>

            <div id="my-recipe-lists">
                <ul class="my-recipe-lists">
                    <% @recipes.each do |recipe| %>
                        <li class="my-recipe-list">
                            <%= link_to recipe_path(recipe.id) do %>
                                <div class="image-content">
                                    <%= image_tag recipe.image, class: "recipe-image" %>
                                </div>
                            <% end %>
                            <div class="recipe-texts">
                                <p class="recipe-title"><%=link_to recipe.title, recipe_path(recipe.id) %></p>
                                <p class="cooking-time">調理時間目安：<%= recipe.cooking_time[:name] %></p>
                                <div class="recipe-texts-flex">
                                    <p class="recipe-user"><%= link_to "投稿者：#{recipe.user.nickname}", user_path(recipe.user_id) %></p>
                                    <div id="fovorite-btn<%= recipe.id %>">
                                        <%= render "favorites/btn", recipe: recipe %>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>

            <div id="my-favorite-lists">
                <ul class="my-recipe-lists">
                    <% @favorited_recipes.each do |favorited_recipe| %>
                        <li class="my-recipe-list">
                            <%= link_to recipe_path(favorited_recipe.id) do %>
                                <div class="image-content">
                                    <%= image_tag favorited_recipe.image, class: "recipe-image" %>
                                </div>
                            <% end %>
                            <div class="recipe-texts">
                                <p class="recipe-title"><%=link_to favorited_recipe.title, recipe_path(favorited_recipe.id) %></p>
                                <p class="cooking-time">調理時間目安：<%= favorited_recipe.cooking_time[:name] %></p>
                                <div class="recipe-texts-flex">
                                    <p class="recipe-user"><%= link_to "投稿者：#{favorited_recipe.user.nickname}", user_path(favorited_recipe.user_id) %></p>
                                    <%= render "favorites/btn", recipe: favorited_recipe %>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

<%= render "shared/footer" %>